# Generated by Django 5.1.7 on 2025-04-13 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0002_hotel"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="hotel",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="hotel.hotel",
            ),
            preserve_default=False,
        ),
    ]
