# Generated by Django 5.1.7 on 2025-04-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0004_booking"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["date_start"]},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="hotel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2025-01-01"),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("room", "date_start", "date_end")},
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["room"], name="hotel_booki_room_id_8ff43f_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["date_start"], name="hotel_booki_date_st_682952_idx"),
        ),
    ]
